<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="ReportGenerator" Version="5.4.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Library\**" />
    <Compile Remove="Library\**" />
    <EmbeddedResource Remove="Library\**" />
    <None Remove="Library\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Temp\**" />
    <Compile Remove="Temp\**" />
    <EmbeddedResource Remove="Temp\**" />
    <None Remove="Temp\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Packages\**" />
    <Compile Remove="Packages\**" />
    <EmbeddedResource Remove="Packages\**" />
    <None Remove="Packages\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Assets\PluginMaster\**" />
    <Compile Remove="Assets\PluginMaster\**" />
    <EmbeddedResource Remove="Assets\PluginMaster\**" />
    <None Remove="Assets\PluginMaster\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Assets\Scripts\FactoryGame\**" />
    <Compile Remove="Assets\Scripts\FactoryGame\**" />
    <EmbeddedResource Remove="Assets\Scripts\FactoryGame\**" />
    <None Remove="Assets\Scripts\FactoryGame\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Assets\Scripts\WorldObjects\**" />
    <Compile Remove="Assets\Scripts\WorldObjects\**" />
    <EmbeddedResource Remove="Assets\Scripts\WorldObjects\**" />
    <None Remove="Assets\Scripts\WorldObjects\**" />
  </ItemGroup>

  <ItemGroup>
      <Reference Include="Assets\Plugins\*.dll" />
      <Reference Include="Assets\Plugins\**\*.dll" />
      <Reference Include="\Applications\Unity\Hub\Editor\**\UnityEngine\*.dll" />
      <Reference Include="X:\unity-editor\**\UnityEngine\*.dll" />
  </ItemGroup>

</Project>
