<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="ReportGenerator" Version="5.4.4" />
  </ItemGroup>

  <!-- !!! IMPORTANT !!! -->
  <!-- !!! THESE VERSIONS MUST BE KEPT IN SYNC -->
  <!-- !!! WITH THE DOWNLOADED DLLS INSIDE OF THE PLUGIN FOLDER -->
  <!-- !!! FAILURE TO DO THIS WILL RESULT IN UNDEFINED BEHAVIOR -->
  <!-- !!! IMPORTANT !!! -->
  <ItemGroup>
    <PackageReference Include="RoyT.AStar" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Library\**" />
    <Compile Remove="Library\**" />
    <EmbeddedResource Remove="Library\**" />
    <None Remove="Library\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Temp\**" />
    <Compile Remove="Temp\**" />
    <EmbeddedResource Remove="Temp\**" />
    <None Remove="Temp\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Assets\Scripts\FactoryGameContent.cs" />
    <Compile Remove="Assets\Scripts\FactoryGameContent.cs" />
    <EmbeddedResource Remove="Assets\Scripts\FactoryGameContent.cs" />
    <None Remove="Assets\Scripts\FactoryGameContent.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Assets\Scripts\FactoryGameController.cs" />
    <Compile Remove="Assets\Scripts\FactoryGameController.cs" />
    <EmbeddedResource Remove="Assets\Scripts\FactoryGameController.cs" />
    <None Remove="Assets\Scripts\FactoryGameController.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Assets\Scripts\GameController.cs" />
    <Compile Remove="Assets\Scripts\GameController.cs" />
    <EmbeddedResource Remove="Assets\Scripts\GameController.cs" />
    <None Remove="Assets\Scripts\GameController.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Assets\Scripts\WorldObjects\**" />
    <Compile Remove="Assets\Scripts\WorldObjects\**" />
    <EmbeddedResource Remove="Assets\Scripts\WorldObjects\**" />
    <None Remove="Assets\Scripts\WorldObjects\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Xunit.Core">
      <HintPath>Assets\Plugins\xunit.core.dll</HintPath>
    </Reference>
    <Reference Include="Xunit.Assert">
      <HintPath>Assets\Plugins\xunit.assert.dll</HintPath>
    </Reference>
    <Reference Include="Xunit.Abstractions">
      <HintPath>Assets\Plugins\xunit.abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Xunit.Execution.DotNet">
      <HintPath>Assets\Plugins\xunit.execution.dotnet.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
